# TODO:
#-   repo: https://github.com/PyCQA/autoflake
#    rev: v2.2.1
#    hooks:
#    -   id: autoflake
#        args: [--remove-all-unused-imports, --in-place]

#repos:
#  - repo: https://github.com/RobertCraigie/pyright-python
#    rev: v1.1.389
#    hooks:
#    - id: pyright