version: "3"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: web_app_pgdb
    tty: true
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}