version: "3.9"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: web_app_pgdb
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: web_app_redis
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    command: sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "user default off" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on allkeys allchannels allcommands >$REDIS_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server --bind 0.0.0.0 --aclfile /usr/local/etc/redis/users.acl
      '
#    volumes:
#      - ./redisdata:/data
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
#    healthcheck:
#      test: [ "CMD", "redis-cli", "-a", "$REDIS_DEFAULT_PASSWORD", "ping" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#    tty: true
#    stdin_open: true