from app.common.constants.api import ROOT_API_PATH

API_VERSION_V1 = "/v1"
API_VERSION_V2 = "/v2"

BASE_BOOKINGS_URL = f"{ROOT_API_PATH}{API_VERSION_V1}/bookings/"
BASE_ROOMS_URL = f"{ROOT_API_PATH}{API_VERSION_V1}/rooms/"
BASE_HOTELS_URL = f"{ROOT_API_PATH}{API_VERSION_V1}/hotels/"
BASE_USERS_URL = f"{ROOT_API_PATH}{API_VERSION_V1}/users/"
BASE_EXPORT_URL = f"{ROOT_API_PATH}{API_VERSION_V1}/export/"
BASE_IMPORT_URL = f"{ROOT_API_PATH}{API_VERSION_V1}/import/"
BASE_SRV_URL_V1 = f"{ROOT_API_PATH}{API_VERSION_V1}/"
BASE_SRV_URL_V2 = f"{ROOT_API_PATH}{API_VERSION_V2}/"
