"""add_query_history

Revision ID:
f91655e89ef9

Revises:
fba4a59078f0

Create Date:
2025-06-10 18:04:11.835569
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f91655e89ef9"
down_revision: Union[str, None] = "fba4a59078f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_history",
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("url_path", sa.String(), nullable=False),
        sa.Column("query_string", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("process_time", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("created_dt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_history")
    # ### end Alembic commands ###
