x-env: &dev-env
  env_file:
    - ../envs/dev.env

services:
  postgres:
    <<: *dev-env

  redis:
    <<: *dev-env

  grafana:
    <<: *dev-env

  celery-worker:
    <<: *dev-env

  celery-flower:
    <<: *dev-env

  api:
    <<: *dev-env
