x-env: &dev-env
  env_file:
    - ../envs/dev.env
  environment:  # TODO: дублирование
    - PYTHONDONTWRITEBYTECODE=1
    - POSTGRES_HOST=postgres
    - REDIS_HOST=redis
    - RMQ_HOST=rabbitmq

services:
  postgres:
    <<: *dev-env

  redis:
    <<: *dev-env

  grafana:
    <<: *dev-env

  rabbitmq:
    <<: *dev-env

  celery-worker:
    <<: *dev-env

  celery-flower:
    <<: *dev-env

  history-consumer:
    <<: *dev-env

  api:
    <<: *dev-env

  frontend:
    <<: *dev-env
