services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    tty: true  # TODO: попробовать стереть и войти в контейнер
    env_file:
      - ../envs/base.env
    ports:
      - 5432:${POSTGRES_PORT}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    env_file:
      - ../envs/base.env
    ports:
      - 6379:${REDIS_PORT}
    command: sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "user default off" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on allkeys allchannels allcommands >$REDIS_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server --bind 0.0.0.0 --aclfile /usr/local/etc/redis/users.acl
      '
#    TODO: разобрать
#    volumes:
#      - ./redisdata:/data
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
#    healthcheck:
#      test: [ "CMD", "redis-cli", "-a", "$REDIS_DEFAULT_PASSWORD", "ping" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#    tty: true
#    stdin_open: true

  celery-worker:
    container_name: celery-worker
    build:
      context: ../
      dockerfile: docker/custom_python/Dockerfile
    env_file:
      - ../envs/base.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    command: ["/code/docker/custom_python/celery.sh", "worker"]
    depends_on:
      - postgres
      - redis
  celery-flower:
    container_name: celery-flower
    build:
      context: ../
      dockerfile: docker/custom_python/Dockerfile
    env_file:
      - ../envs/base.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - 5555:${FLOWER_PORT}
    command: ["/code/docker/custom_python/celery.sh", "flower", "${FLOWER_PORT}"]
    depends_on:
      - postgres
      - redis

  api:
    container_name: api
    build:
      context: ../
      dockerfile: docker/custom_python/Dockerfile
    env_file:
      - ../envs/base.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - 8010:${PORT}
    command: ["/code/docker/custom_python/api.sh"]
    depends_on:
      - celery-worker
      - celery-flower
      - postgres
      - redis