from app.common.constants.paths import (
    API_V1_PATH,
    API_V2_PATH,
    BOOKINGS_PATH,
    EXPORT_PATH,
    HOTELS_PATH,
    IMPORT_PATH,
    PING_PATH,
    ROOMS_PATH,
    ROOT_API_PATH,
    SIGN_IN_PATH,
    SIGN_OUT_PATH,
    SIGN_UP_PATH,
    USERS_CURRENT_PATH,
    USERS_PATH,
)

ROOT_V1 = f"{ROOT_API_PATH}{API_V1_PATH}"
ROOT_V2 = f"{ROOT_API_PATH}{API_V2_PATH}"

BOOKINGS_URL = f"{ROOT_V1}{BOOKINGS_PATH}/"
ROOMS_URL = f"{ROOT_V1}{ROOMS_PATH}/"
HOTELS_URL = f"{ROOT_V1}{HOTELS_PATH}/"

ROOT_V1_USERS = f"{ROOT_V1}{USERS_PATH}"
USERS_URL = f"{ROOT_V1_USERS}/"
USERS_CURRENT_URL = f"{ROOT_V1_USERS}{USERS_CURRENT_PATH}"
USERS_SIGN_IN_URL = f"{ROOT_V1_USERS}{SIGN_IN_PATH}"
USERS_SIGN_OUT_URL = f"{ROOT_V1_USERS}{SIGN_OUT_PATH}"
USERS_SIGN_UP_URL = f"{ROOT_V1_USERS}{SIGN_UP_PATH}"

ROOT_V1_EXPORT = f"{ROOT_V1}{EXPORT_PATH}"
EXPORT_URL = f"{ROOT_V1_EXPORT}/"

ROOT_V1_IMPORT = f"{ROOT_V1}{IMPORT_PATH}"
IMPORT_URL = f"{ROOT_V1_IMPORT}/"

PING_V1_URL = f"{ROOT_V1}{PING_PATH}"
PING_V2_URL = f"{ROOT_V2}{PING_PATH}"
